package core;

import java.sql.*;

/**
 * SQLite -> PostgreSQL 数据迁移工具
 * 用法: java -cp gsl5.jar;lib/postgresql-42.7.3.jar core.MigrateDb [pgHost] [pgPort] [pgDb] [pgUser] [pgPass]
 * 默认: 127.0.0.1 5432 gsl5 gsl5
 */
public class MigrateDb {

    public static void main(String[] args) {
        String pgHost = args.length > 0 ? args[0] : "127.0.0.1";
        String pgPort = args.length > 1 ? args[1] : "5432";
        String pgDb   = args.length > 2 ? args[2] : "gsl5";
        String pgUser = args.length > 3 ? args[3] : "gsl5";
        String pgPass = args.length > 4 ? args[4] : "";

        String pgUrl = "jdbc:postgresql://" + pgHost + ":" + pgPort + "/" + pgDb;

        try {
            Class.forName("org.sqlite.JDBC");
            Class.forName("org.postgresql.Driver");
        } catch (Exception e) {
            System.err.println("Driver not found: " + e.getMessage());
            System.exit(1);
        }

        try (Connection sqlite = DriverManager.getConnection("jdbc:sqlite:data.db");
             Connection pg = DriverManager.getConnection(pgUrl, pgUser, pgPass)) {

            pg.setAutoCommit(false);
            System.out.println("Connected to SQLite and PostgreSQL.");

            // Ensure PG tables exist
            ensurePgTables(pg);

            // Migrate each table
            int total = 0;
            total += migrateTable(sqlite, pg, "shell", new String[]{
                "id","url","password","secretKey","payload","cryption","encoding",
                "headers","reqLeft","reqRight","connTimeout","readTimeout",
                "proxyType","proxyHost","proxyPort","remark","note","createTime","updateTime"
            }, "id");
            total += migrateTable(sqlite, pg, "shellEnv", new String[]{"shellId","key","value"}, null);
            total += migrateTable(sqlite, pg, "plugin", new String[]{"pluginJarFile"}, null);
            total += migrateTable(sqlite, pg, "seting", new String[]{"key","value"}, "key");
            total += migrateTable(sqlite, pg, "shellGroup", new String[]{"groupId"}, null);

            pg.commit();
            System.out.println("\nDone. Total rows migrated: " + total);

        } catch (Exception e) {
            System.err.println("Migration failed: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private static void ensurePgTables(Connection pg) throws SQLException {
        try (Statement s = pg.createStatement()) {
            s.execute("CREATE TABLE IF NOT EXISTS shell (" +
                "id VARCHAR(64) PRIMARY KEY, url TEXT NOT NULL, password TEXT NOT NULL, " +
                "secretKey TEXT NOT NULL, payload TEXT NOT NULL, cryption TEXT NOT NULL, " +
                "encoding TEXT NOT NULL, headers TEXT, reqLeft TEXT, reqRight TEXT, " +
                "connTimeout INTEGER DEFAULT 60000, readTimeout INTEGER DEFAULT 60000, " +
                "proxyType TEXT, proxyHost TEXT, proxyPort TEXT, remark TEXT, note TEXT, " +
                "createTime TEXT, updateTime TEXT)");
            s.execute("CREATE TABLE IF NOT EXISTS shellEnv (" +
                "shellId VARCHAR(64) NOT NULL, key VARCHAR(256) NOT NULL, value TEXT, " +
                "PRIMARY KEY (shellId, key))");
            s.execute("CREATE TABLE IF NOT EXISTS plugin (" +
                "pluginJarFile VARCHAR(512) PRIMARY KEY)");
            s.execute("CREATE TABLE IF NOT EXISTS seting (" +
                "key VARCHAR(256) PRIMARY KEY, value TEXT)");
            s.execute("CREATE TABLE IF NOT EXISTS shellGroup (" +
                "groupId VARCHAR(256) PRIMARY KEY)");
            s.execute("CREATE TABLE IF NOT EXISTS operation_log (" +
                "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "username VARCHAR(128) NOT NULL, shell_id VARCHAR(64), " +
                "action VARCHAR(128) NOT NULL, detail TEXT, create_time TEXT NOT NULL)");
        }
        System.out.println("PG tables ready.");
    }

    private static int migrateTable(Connection sqlite, Connection pg, String table,
                                     String[] columns, String pkColumn) throws SQLException {
        // Read from SQLite
        String sql = "SELECT * FROM " + table;
        int count = 0;
        try (Statement rs = sqlite.createStatement();
             ResultSet rsSet = rs.executeQuery(sql)) {

            // Build PG INSERT ... ON CONFLICT DO NOTHING
            StringBuilder colList = new StringBuilder();
            StringBuilder valList = new StringBuilder();
            for (int i = 0; i < columns.length; i++) {
                if (i > 0) { colList.append(","); valList.append(","); }
                colList.append(columns[i]);
                valList.append("?");
            }
            String insertSql = "INSERT INTO " + table + " (" + colList + ") VALUES (" + valList + ")";
            if (pkColumn != null) {
                insertSql += " ON CONFLICT (" + pkColumn + ") DO NOTHING";
            }

            try (PreparedStatement ps = pg.prepareStatement(insertSql)) {
                while (rsSet.next()) {
                    for (int i = 0; i < columns.length; i++) {
                        ps.setObject(i + 1, rsSet.getObject(i + 1));
                    }
                    ps.addBatch();
                    count++;
                }
                ps.executeBatch();
            }
        }
        System.out.println("  " + table + ": " + count + " rows");
        return count;
    }
}